version: '3'

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      target: backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo:latest
